[package]
name = "conway-rust"
version = "0.1.0"
authors = ["jdelman <joshdelman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
base64 = "0.10.1"